name: 'Check'

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: 'Install'
        run: yarn install

      - name: 'Run tests'
        run: yarn test
